name: flutter_plugin
description: A Flutter plugin for blockchain integration

version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
