name: atlas_blockchain_flutter
description: ATLAS Blockchain Flutter mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  
  # Crypto & Security
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  convert: ^3.1.1
  web3dart: ^2.7.1
  bip39: ^1.0.6
  hex: ^0.2.0
  eth_sig_util: ^0.0.9
  
  # Reactive Programming
  rxdart: ^0.27.7
  
  # UI Components
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  
  # Navigation
  go_router: ^10.1.2
  
  # Utilities
  logger: ^2.0.2
  intl: ^0.18.1
  
  # Additional UI
  cached_network_image: ^3.3.0
  fl_chart: ^0.63.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  google_fonts: ^6.1.0
  file_picker: ^6.1.1
  file_saver: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # Fonts matching web CSS
  # Temporarily comment out fonts for testing
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-ExtraBold.ttf
  #         weight: 800