name: atlas_blockchain_flutter
description: ATLAS Blockchain Flutter mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^9.1.1 # Keep as is, no conflict
  bloc: ^9.0.1 # Keep as is
  equatable: ^2.0.5
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.3
  shared_preferences_web: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  
  # Crypto & Security
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  convert: ^3.1.1
  web3dart: ^2.7.3
  hex: ^0.2.0
  ed25519_hd_key: ^2.3.0
  bip39: ^1.0.6
  pinenacl: ^0.6.0
  
  # Reactive Programming
  
  # UI Components
  flutter_svg: ^2.2.1
  lottie: ^3.3.2
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  go_router: ^16.2.4
  smooth_page_indicator: ^1.1.0  # Added for onboarding slider
  
  # Utilities
  logger: ^2.0.2
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  encrypt: ^5.0.3
  
  # Additional UI
  cached_network_image: ^3.3.0
  fl_chart: ^1.1.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  google_fonts: ^6.3.2
  file_picker: ^10.3.3
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
